version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo_dev
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWD}
      - MONGO_DB=flashcards
    networks:
      - shared-network-dev
    volumes:
      - ./mongo-db:/data/db

  api:
    container_name: api_dev
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - MONGODB=mongodb://${MONGO_USER}:${MONGO_PASSWD}@mongo
      - NODE_ENV=${NODE_ENV}
    build:
      context: ./Flashcards
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    networks:
      - shared-network-dev
    volumes:
      - ./Flashcards:/app/api
    depends_on:
      - mongo

  client:
    container_name: client_dev
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    build:
      context: ./flashcards-react
    ports:
      - 3000:3000
    networks:
      - shared-network
    volumes:
      - ./flashcards-react:/app/client
    depends_on:
      - api

networks:
  shared-network-dev:
